---
layout: default
title: "자바 기본내용(try-catch)"
---
 
## Try-Catch

> ## 1. throws를 통해 오류를 관리하는 경우
>
> 먼저 기본 Exception 클래스를 상속받아 사용자가 재정의하는 새로운 Exception class를 만들 수 있습니다. 
>
> 아래의 DataNotFoundException, DuplicatedException이 그 예시입니다. 
>
> 이와 같이 Exception class를 지정해 주는 이유는 프로그램 구동 도중 발생할 수 있는 오류들에 대한 사후처리를 
>
> 개발자가 원하는 방향으로 해줄 수 있다는 장점을 지닙니다.

```java
// DuplicatedException.java
public class DuplicatedException extends Exception{
	public DuplicatedException() {};
	public DuplicatedException(String id) {
		super("등록을 원하시는 "+id+"에 대해서 중복된 데이터가 존재합니다");
	}
}

// Main.java
// 중략...
} catch (DuplicatedException e) {
	System.out.println("오류코드2: " + e.getMessage());
	continue;
// 중략...
```

> ## 2. 예상할 수 있는 외부 오류가 발생하여도 프로그램이 계속해서 실행할 수 있도록 하는 경우
> 기본적으로 예외처리를 해주지 않은 프로그램에서는 오류 발생 시, 프로그램이 죽게됩니다. 
>
> 하지만 예외가 발생하는 상황은 매우 많으며 그 문제는 http통신이나 파일오픈 등 
>
> 개발자가 직접 관리하기 힘든 영역에서 발생할 수 있습니다. 
>
> 예를 들어, 서버에서 데이터를 받아와 데이터베이스에 저장하는 프로그램이 있다고 가정한다면 
>
> (1)서버 오류가 발생하는 경우 
>
> (2) 데이터를 데이터베이스에 저장하기 위한 처리작업에서 오류가 발생한 경우 
>
> (3) 데이터베이스에 저장하는 과정에서 데이터베이스 서버 등 문제가 발생할 경우
>
> 라는 세 부분에서 문제가 발생할 수 있습니다. 이때 적절한 예외처리를 해주지 못한 경우 
>
> 프로그램은 각 상황에서 죽게되지만 예외처리를 해주는 경우 오류에 대해 대처가 가능하다는 이점을 얻게됩니다. 
>
> 예를 들어 외부 서버에 접속해서 1~100개의 정보를 받는 상황을 가정하고 55번 정보까지 받은 상황에서 
>
> 오류가 발생하는 상황을 가정합니다.이때 오류 로그를 파일로 기록하고
>
> (ex 내용은 지금까지 받은 최종 정보는 55번 등의 내용이 작성될 수 있습니다) 
>
> 서버의 정상화가 확인되면 다시 서버에 접속해 해당 오류 로그를 통해 1번 정보부터 다시 받아오지 않고 
>
> 56번 정보부터 받아오는  프로그램을 만들 수 있습니다. 
